version: '3.8'

services:
  pe-dashboard:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_THEME_PRIMARY_COLOR=#1f77b4
      - STREAMLIT_THEME_BACKGROUND_COLOR=#ffffff
    volumes:
      - .:/app
    restart: unless-stopped
